// Angular/poke-agenda/src/app/poke-agenda/poke-agenda.component.ts
import { Component, OnInit } from '@angular/core';

const MAX_POKE: number = 151;

@Component({
  selector: 'app-poke-agenda',
  templateUrl: './poke-agenda.component.html',
  styleUrls: ['./poke-agenda.component.scss']
})
export class PokeAgendaComponent implements OnInit {

	id : number;
	mode: String;
	disabled_prev : Boolean;
	disabled_next : Boolean;
	failure :  Boolean;

  constructor() {
  	this.id = 1;
  	this.mode = "pokemon"; 
  	this.disabled_prev = true;
  	this.disabled_next = false;
  	this.failure = false;
  }

  prev(){
  	if(this.id>1){
      this.id -= 1;
      this.disabled_prev = true;
      this.disabled_next = true;
    }
  }

  next(){
  	if(this.id<MAX_POKE){
      this.id +=1;
      this.disabled_prev = true;
      this.disabled_next = true;
    }
  }

  desalock(){

    let d_next = false;
    let d_prev = false;

    if(this.id===1){
      d_prev = true;
    }else{
      if(this.id === MAX_POKE){
      	d_next = true;
      }
    }

    this.disabled_prev = d_prev;
    this.disabled_next = d_next;
  }

  responseRequest(event){
      
    let f=false;

    if(this.failure || event.failure){
      f = true;
    }

    this.failure = f;
    this.id = event.newID;

    if(event.failure){
      this.desalock();
    }
  }

  ngOnInit(): void {
  
  }

  onSearch(event){
  	this.id = event.target.value.toLowerCase();
    this.disabled_prev = true;
    this.disabled_next = true; 
  }

  onClose(event){
  	this.failure = false;
  }
}

<div class='PokemonName'>
	<h1>PokéAgenda-Angular </h1>
	<app-searcher [failure]="failure" (search)="onSearch($event)" (close)="onClose($event)"></app-searcher>
	<div class="carousel">
      <button type="button" id = 'prev' class="btn btn-primary" (click)="prev()" [disabled]="disabled_prev"> &#60; </button>
      <!--<Pokemon  :poke_id="id" :max_poke="max_poke" @modify="desalock" @request="responseRequest"/>-->
      <app-pokemon [poke_id]="id" (modify)="desalock()" (request)="responseRequest($event)"></app-pokemon>
      <button type="button" id = 'next' class="btn btn-primary" (click)="next()" [disabled]="disabled_next"> > </button>
  </div>
</div>

// React/poke-agenda/src/poke_agenda/poke_agenda.js
import React from 'react';

import Button from 'react-bootstrap/Button';

import Pokemon from '../pokemon/Pokemon'
import Searcher from '../searcher/Searcher'

import 'bootstrap/dist/css/bootstrap.min.css';
import './poke_agenda.css'

class PokeAgenda extends React.Component{

	max_poke = 151;

	constructor(props) {
  	super(props);
    
    this.state = {
      id : 1,
      mode: 'pokemon',
      disabled_prev: true,
      disabled_next: false,
      search_failure: false 
  	}

    this.desalock = this.desalock.bind(this);
    this.search = this.search.bind(this);
    this.closeAlert = this.closeAlert.bind(this);
    this.responseRequest = this.responseRequest.bind(this);
  }	

  prev(){
  	if(this.state.id>1){
  		this.setState((state,props)=>({
        id : state.id-1,
        disabled_prev: true,
        disabled_next: true
      }));
  	}
  }

  next(){
  	if(this.state.id<this.max_poke){
  		this.setState((state,props)=>({
  			id : state.id+1,
        disabled_prev: true,
        disabled_next: true
  		}));
  	}
  }

  search(event){
    if(event.keyCode === 13){
      this.setState({
        id : event.target.value.toLowerCase()
      });
    }else{
      this.setState({
        search_failure : false
      });
    }
  }

  closeAlert(event){
      this.setState({
        search_failure : false
      });
  }

  responseRequest(failure,newID,pokeName){
    let f=false;

    if(this.state.search_failure || failure){
      f = true;
    }

    this.setState((state,props) => ({
      id: newID,
      poke_name : pokeName.toLowerCase(),
      search_failure: f
    })); 
  }

  desalock(event){

    let d_next = false;
    let d_prev = false;

    if(this.state.id===1){
      d_prev = true;
    }else{
      if(this.state.id === this.max_poke){
        d_next = true;
      }
    }

    this.setState({    
      disabled_prev: d_prev,
      disabled_next: d_next
    });
  }

  render(){
  	
  	let page = {};
  	switch(this.state.mode){
  		case 'pokemon' :
  			page =	<div className='PokemonName'>
                  <h1>PokéAgenda-React </h1>
                  <Searcher search_failure={this.state.search_failure} onKeyUp={this.search} onCloseAlert={this.closeAlert}/>
  								<div className='carousel'>
                    <Button  id = 'prev' onClick={event => this.prev(event)} disabled={this.state.disabled_prev} size='lg'  > &#60; </Button>
                    <Pokemon poke_id={this.state.id} onModify={this.desalock} onRequest={this.responseRequest}/>
                    <Button id = 'next' onClick={event => this.next(event)} disabled={this.state.disabled_next} size='lg'> > </Button>  						 			
  						 		</div>
  						 	</div>;
  		break;
  		default:
  			page = <div></div>;
  	}

  	return page;

  }

}

export default PokeAgenda;
