// Svelte/poke-agenda/src/Pokemon.svelte
<main>
	<h1>Pokemon</h1>
</main>

<script>
	
</script>

<style>
	.PokeImage{
	  width: 30%;
	}

	.header{
	  display: inline-flex;
	}

	.item{
	  margin-top: 5px;
	  margin-bottom: 5px;
	}

	.itemAbility{
	  margin-right: 2%;
	  margin-left: 2%;
	}

	.itemStats{
	  margin-right: 5%;
	  margin-left: 5%;
	}

	.name{
	  display: inline;
	  margin-right: 10px;
	  margin-bottom: 0px;
	}

	.logosTypes{
	  margin: auto auto;
	  display: grid;
	  align-content: center;
	  align-items: center;
	}

	.icon {
	    border-radius: 50%;
	    height: 30px;
	    width: 30px;
	    display: inline;
	    margin-right: 5px;
	}

	.divAbilities{
	  display: inline-flex;
	}

	.abilities{
	  margin: auto auto;
	  display: grid;
	  align-content: center;
	  align-items: center;
	}

	.pAbility{
	  margin-bottom: 0px;
	  display: inline;
	}

	.star{
	  color: yellow;
	  display: inline;
	}

	.stats{
	  width: 100%;
	  margin: auto auto;
	  display: grid;
	  grid-template-columns: 100px 40px 1fr;
	  align-content: center;
	  align-items: center;
	}

	.divProgressBar{
	  margin-bottom: 8px;
	}

	.bg-hp{
	  background-color: red;
	}

	.bg-atk{
	  background-color: orange;
	}

	.bg-def{
	  background-color: yellow;
	}

	.bg-spAtk{
	  background-color: blue;
	}

	.bg-spDef{
	  background-color: green;
	}

	.bg-speed{
	  background-color: pink;
	}
</style>

// Vue/poke-agenda/src/components/Pokemon.vue
<template>
  <div >
  </div>  
</template>

<script>
  export default {
    data: () => ({
      id : 1,
      name : '',
      sprites: {},
      stats : [{base_stat : 0},{base_stat : 0},{base_stat : 0}, {base_stat : 0},{base_stat: 0},{base_stat:0}],
      types: [],
      abilities: [] 
    })
  }
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style>

.PokeImage{
  width: 30%;
}

.header{
  display: inline-flex;
}

.item{
  margin-top: 5px;
  margin-bottom: 5px;
}

.itemAbility{
  margin-right: 2%;
  margin-left: 2%;
}

.itemStats{
  margin-right: 5%;
  margin-left: 5%;
}

.name{
  display: inline;
  margin-right: 10px;
  margin-bottom: 0px;
}

.logosTypes{
  margin: auto auto;
  display: grid;
  align-content: center;
  align-items: center;
}

.icon {
    border-radius: 50%;
    height: 30px;
    width: 30px;
    display: inline;
    margin-right: 5px;
}

.divAbilities{
  display: inline-flex;
}

.abilities{
  margin: auto auto;
  display: grid;
  align-content: center;
  align-items: center;
}

.pAbility{
  margin-bottom: 0px;
  display: inline;
}

.star{
  color: yellow;
  display: inline;
}

.stats{
  width: 100%;
  margin: auto auto;
  display: grid;
  grid-template-columns: 100px 40px 1fr;
  align-content: center;
  align-items: center;
}

.divProgressBar{
  margin-bottom: 8px;
}

.bg-hp{
  background-color: red;
}

.bg-atk{
  background-color: orange;
}

.bg-def{
  background-color: yellow;
}

.bg-spAtk{
  background-color: blue;
}

.bg-spDef{
  background-color: green;
}

.bg-speed{
  background-color: pink;
}
</style>
