// Angular/poke-agenda/src/app/searcher/searcher.component.ts
import { Component, OnInit, ViewChild, ElementRef,EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-searcher',
  templateUrl: './searcher.component.html',
  styleUrls: ['./searcher.component.scss']
})
export class SearcherComponent implements OnInit {
	
  @Input() failure: Boolean;

  //Events
	@Output() search = new EventEmitter();
	@Output() close = new EventEmitter();

	//Reference
	@ViewChild("searchInput") searchInput: ElementRef; 

  constructor() {
  }

  onSendText(event){
  	this.search.emit(event);
  }

  onCloseAlert(event){
  	this.failure = false;
  	this.close.emit(event);
  	this.searchInput.nativeElement.focus();
  }

  ngOnInit(): void {

  }

}

<div>
  <div class="searchBar">
  	<input #searchInput id="typeahead-basic" type="text" placeholder="Search..." class="form-control" (keyup.enter)="onSendText($event)"/>
  </div>
  <!--<ngb-alert :show="failure" variant="danger" @dismissed="closeDialog" dismissible>-->
  <ngb-alert *ngIf="failure" type="danger" (close)="onCloseAlert($event)">
    Pokemon not found!!!
  </ngb-alert>
</div>

// Vue/poke-agenda/src/components/Searcher.vue
<template>
  <div>
    <b-form-group  class="searchBar">
      <b-form-input ref="search" v-model="text" @keyup.enter.native="searchID" type="text" placeholder="Search..." />
    </b-form-group>
    <b-alert :show="failure" variant="danger" @dismissed="closeDialog" dismissible>
      Pokemon not found!!!
    </b-alert>
  </div>  
</template>

<script>
  export default {
    props: ['failure'],
    data: () => ({
      text: ''
    }),
    mounted() {
      this.$refs.search.focus();
    },
    updated(){
      this.$nextTick(() => {

      });
    },
    methods: {
      searchID(){
        this.$emit('search',this.text);
        this.$refs.search.focus();
      },
      closeDialog(){
        this.$emit('close');
        this.$refs.search.focus();
      }
    }
  }
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style>
  
  .searchBar{
    margin-right: 20%;
    margin-left: 20%;
  }

</style>
