// Vue/poke-agenda/src/components/Searcher.vue
<template>
  <div>
    <b-form-group  class="searchBar">
      <b-form-input ref="search" v-model="text" @keyup.enter.native="searchID" type="text" placeholder="Search..." />
    </b-form-group>
    <b-alert v-model="search_failure" variant="danger" @dismissed="closeDialog('teste')" dismissible>
      Pokemon not found!!!
    </b-alert>
  </div>  
</template>

<script>
  export default {
    props: ['failure'],
    data: (props) => ({
      search_failure: props.failure,
      text: ''
    }),
    mounted() {
      this.$refs.search.focus();
    },
    methods: {
      closeDialog() {
        this.$refs.search.focus();
      },
      searchID(){
        this.$emit('search',this.text);
        this.$refs.search.focus();
      }
    }
  }
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style>
  
  .searchBar{
    margin-right: 20%;
    margin-left: 20%;
  }

</style>

// React/poke-agenda/src/searcher/Searcher.js
import React from 'react';

import Alert from 'react-bootstrap/Alert';
import Form from 'react-bootstrap/Form';

import './searcher.css'

class Searcher extends React.Component{
 
  constructor(props) {
  	super(props);
    this.textInput = React.createRef();
    this.state = {
      failure : false
  	}
  }	

  componentDidMount() {
		 this.textInput.current.focus();
	}

	componentDidUpdate(prevProps){

    if(prevProps.search_failure !== this.props.search_failure){
      this.setState((state, props) => ({
        failure : props.search_failure
      }));
      this.textInput.current.focus();   
    }

	}

  render(){

  	let page={};

  	let alert = [];

  	if(this.state.failure){
  		alert = <Alert variant="danger" onClose={event => this.props.onCloseAlert(event)} dismissible>
  							<Alert.Heading>Pokemon not found!!!</Alert.Heading>
  						</Alert>
  	}

  	page = 	<div>
              <Form.Group className='searchBar'>
              	<Form.Control ref={this.textInput} type='text' placeholder='Search...' onKeyUp={ event => this.props.onKeyUp(event)}/>
              </Form.Group>
            	{alert}
            </div>

		return page;
  }
}

export default Searcher;
