// Svelte/poke-agenda/src/PokeAgenda.svelte
<main>
	<div class='PokemonName'>
    <h2>PokéAgenda-Svelte </h2>
    <!--<Searcher :failure="failure" @close="close" @search="search"/>-->
    <Searcher {failure} on:close={onClose} on:search={onSearch}/>
    <div class="carousel">
      <Button id="prev" color='primary' size ='lg'>  &#60; </Button>
    	<Pokemon/>
    	<Button id="next" color='primary' size='lg'> > </Button>
      
      <!--
      <b-button id = 'prev' @click="prev" :disabled="disabled_prev" size='lg'> &#60; </b-button>
      <Pokemon  :poke_id="id" :max_poke="max_poke" @modify="desalock" @request="responseRequest"/>
      <b-button id = 'next' @click="next" :disabled="disabled_next" size='lg'> > </b-button>
    	-->
    </div>
  </div> 
</main>

<script>
	import { onMount } from 'svelte'


	import Searcher from './Searcher.svelte';
	import Pokemon from './Pokemon.svelte';
	
	import { Button } from 'sveltestrap';

	let id = 1;
	let failure = true;
	let disabled_prev = true;
	let disabled_next = false;
	let max_poke = 151;
 
	function onSearch(event) {
      id = event.detail.toLowerCase();
      disabled_prev = true;
      disabled_next = true;
  }

  function onClose(){
    failure = false;
  }

</script>

<style>
	.PokemonName{
    margin: 0 auto;
    width: 50%;
    padding: 5px;
    text-align: center;
  }

  .carousel{
    margin: auto auto;
    display: grid;
    grid-template-columns: auto 1fr auto;
    align-content: center;
    align-items: center;
  }
</style>

// Angular/poke-agenda/src/app/poke-agenda/poke-agenda.component.ts
import { Component, OnInit } from '@angular/core';

const MAX_POKE: number = 151;

@Component({
  selector: 'app-poke-agenda',
  templateUrl: './poke-agenda.component.html',
  styleUrls: ['./poke-agenda.component.scss']
})
export class PokeAgendaComponent implements OnInit {

	id : number;
	mode: String;
	disabled_prev : Boolean;
	disabled_next : Boolean;
	failure :  Boolean;

  constructor() {
  	this.id = 1;
  	this.mode = "pokemon"; 
  	this.disabled_prev = true;
  	this.disabled_next = false;
  	this.failure = false;
  }

  prev(){
  	if(this.id>1){
      this.id -= 1;
      this.disabled_prev = true;
      this.disabled_next = true;
    }
  }

  next(){
  	if(this.id<MAX_POKE){
      this.id +=1;
      this.disabled_prev = true;
      this.disabled_next = true;
    }
  }

  desalock(){

    let d_next = false;
    let d_prev = false;

    if(this.id===1){
      d_prev = true;
    }else{
      if(this.id === MAX_POKE){
      	d_next = true;
      }
    }

    this.disabled_prev = d_prev;
    this.disabled_next = d_next;
  }

  responseRequest(event){
      
    let f=false;

    if(this.failure || event.failure){
      f = true;
    }

    this.failure = f;
    this.id = event.newID;

    if(event.failure){
      this.desalock();
    }
  }

  ngOnInit(): void {
  
  }

  onSearch(event){
  	this.id = event.target.value.toLowerCase();
    this.disabled_prev = true;
    this.disabled_next = true; 
  }

  onClose(event){
  	this.failure = false;
  }
}

<div class='PokemonName'>
	<h1>PokéAgenda-Angular </h1>
	<app-searcher [failure]="failure" (search)="onSearch($event)" (close)="onClose($event)"></app-searcher>
	<div class="carousel">
      <button type="button" id = 'prev' class="btn btn-primary" (click)="prev()" [disabled]="disabled_prev"> &#60; </button>
      <!--<Pokemon  :poke_id="id" :max_poke="max_poke" @modify="desalock" @request="responseRequest"/>-->
      <app-pokemon [poke_id]="id" (modify)="desalock()" (request)="responseRequest($event)"></app-pokemon>
      <button type="button" id = 'next' class="btn btn-primary" (click)="next()" [disabled]="disabled_next"> > </button>
  </div>
</div>
